export { default as NavBar } from "./NavBar";
export { default as About } from "./About";
export { default as Projects } from "./Projects";
export { default as ProjectCard } from "./ProjectCard";
export { default as Skills } from "./Skills";
export { default as Certificates } from "./Certificates";
export { default as CertificateCard } from "./CertificateCard";
export { default as Footer } from "./Footer";
export { default as ScrollButton } from "./UI/ScrollButton";
